version: "3.7"

services:
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /src
    entrypoint: /entrypoint.sh
    volumes:
      - ./:/src
    depends_on:
      - db
